/**
 * Reflections & Persona Changes API routes
 */

import { createRoute, OpenAPIHono, z } from "@hono/zod-openapi";
import { clerkAuth, getAuthUserId } from "../middleware/clerk-auth";
import { ErrorResponseSchema } from "../schemas/common";
import {
	ListPersonaChangesResponseSchema,
	ListReflectionsResponseSchema,
} from "../schemas/reflections";
import type { Bindings } from "../types/bindings";
import type { AgentReflection, PersonaChange } from "../types/database";
import { forbidden, handleDatabaseError, notFound } from "../utils/errors";

const reflections = new OpenAPIHono<{ Bindings: Bindings }>();

reflections.use("/*", clerkAuth);

// GET /agents/{agentId}/reflections
const listReflectionsRoute = createRoute({
	method: "get",
	path: "/agents/{agentId}/reflections",
	tags: ["Feedbacks"],
	summary: "List agent's reflections",
	description: "Get reflections (questions) generated by the agent after sessions",
	security: [{ bearerAuth: [] }],
	request: {
		params: z.object({
			agentId: z
				.string()
				.uuid()
				.openapi({
					param: { name: "agentId", in: "path" },
					description: "Agent ID",
				}),
		}),
		query: z.object({
			unanswered: z
				.string()
				.optional()
				.openapi({
					param: { name: "unanswered", in: "query" },
					description: "Filter to only unanswered reflections (true/false)",
				}),
		}),
	},
	responses: {
		200: {
			description: "List of reflections",
			content: { "application/json": { schema: ListReflectionsResponseSchema } },
		},
		401: {
			description: "Unauthorized",
			content: { "application/json": { schema: ErrorResponseSchema } },
		},
		403: {
			description: "Forbidden",
			content: { "application/json": { schema: ErrorResponseSchema } },
		},
		404: {
			description: "Agent not found",
			content: { "application/json": { schema: ErrorResponseSchema } },
		},
		500: {
			description: "Internal server error",
			content: { "application/json": { schema: ErrorResponseSchema } },
		},
	},
});

reflections.openapi(listReflectionsRoute, async (c) => {
	const userId = getAuthUserId(c);
	const { agentId } = c.req.valid("param");
	const { unanswered } = c.req.valid("query");

	try {
		const agent = await c.env.DB.prepare("SELECT user_id FROM agents WHERE id = ?")
			.bind(agentId)
			.first<{ user_id: string }>();

		if (!agent) return notFound(c, "Agent");
		if (agent.user_id !== userId) return forbidden(c, "You do not have access to this agent");

		let result: D1Result<AgentReflection>;
		if (unanswered === "true") {
			result = await c.env.DB.prepare(
				`SELECT ar.id, ar.agent_id, ar.session_id, ar.question, ar.context_summary, ar.created_at
				 FROM agent_reflections ar
				 LEFT JOIN feedbacks f ON f.reflection_id = ar.id
				 WHERE ar.agent_id = ? AND f.id IS NULL
				 ORDER BY ar.created_at DESC LIMIT 30`,
			)
				.bind(agentId)
				.all<AgentReflection>();
		} else {
			result = await c.env.DB.prepare(
				`SELECT id, agent_id, session_id, question, context_summary, created_at
				 FROM agent_reflections WHERE agent_id = ?
				 ORDER BY created_at DESC LIMIT 30`,
			)
				.bind(agentId)
				.all<AgentReflection>();
		}

		return c.json({ reflections: result.results });
	} catch (error) {
		return handleDatabaseError(c, error);
	}
});

// GET /agents/{agentId}/persona-changes
const listPersonaChangesRoute = createRoute({
	method: "get",
	path: "/agents/{agentId}/persona-changes",
	tags: ["Feedbacks"],
	summary: "List agent's persona change history",
	description: "Get the history of persona changes for an agent",
	security: [{ bearerAuth: [] }],
	request: {
		params: z.object({
			agentId: z
				.string()
				.uuid()
				.openapi({
					param: { name: "agentId", in: "path" },
					description: "Agent ID",
				}),
		}),
	},
	responses: {
		200: {
			description: "List of persona changes",
			content: { "application/json": { schema: ListPersonaChangesResponseSchema } },
		},
		401: {
			description: "Unauthorized",
			content: { "application/json": { schema: ErrorResponseSchema } },
		},
		403: {
			description: "Forbidden",
			content: { "application/json": { schema: ErrorResponseSchema } },
		},
		404: {
			description: "Agent not found",
			content: { "application/json": { schema: ErrorResponseSchema } },
		},
		500: {
			description: "Internal server error",
			content: { "application/json": { schema: ErrorResponseSchema } },
		},
	},
});

reflections.openapi(listPersonaChangesRoute, async (c) => {
	const userId = getAuthUserId(c);
	const { agentId } = c.req.valid("param");

	try {
		const agent = await c.env.DB.prepare("SELECT user_id FROM agents WHERE id = ?")
			.bind(agentId)
			.first<{ user_id: string }>();

		if (!agent) return notFound(c, "Agent");
		if (agent.user_id !== userId) return forbidden(c, "You do not have access to this agent");

		const result = await c.env.DB.prepare(
			`SELECT id, agent_id, feedback_id, persona_before, persona_after, created_at
			 FROM persona_changes WHERE agent_id = ?
			 ORDER BY created_at DESC LIMIT 50`,
		)
			.bind(agentId)
			.all<PersonaChange>();

		return c.json({ persona_changes: result.results });
	} catch (error) {
		return handleDatabaseError(c, error);
	}
});

export { reflections as reflectionsRouter };
