-- Migration: Agent Reflections and Persona Changes
-- Supports Issue #13 (agent-initiated feedback) and Issue #14 (persona change visualization)

-- Agent reflections: questions generated by agents after sessions
CREATE TABLE IF NOT EXISTS agent_reflections (
    id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    question TEXT NOT NULL,
    context_summary TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (agent_id) REFERENCES agents(id),
    FOREIGN KEY (session_id) REFERENCES sessions(id),
    UNIQUE(agent_id, session_id)
);

-- Persona changes: tracks before/after persona diffs when feedback is applied
CREATE TABLE IF NOT EXISTS persona_changes (
    id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL,
    feedback_id TEXT NOT NULL,
    persona_before TEXT NOT NULL,
    persona_after TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (agent_id) REFERENCES agents(id),
    FOREIGN KEY (feedback_id) REFERENCES feedbacks(id)
);

CREATE INDEX IF NOT EXISTS idx_persona_changes_agent_id ON persona_changes(agent_id);

-- Add reflection_id to feedbacks to link feedback to agent reflection
ALTER TABLE feedbacks ADD COLUMN reflection_id TEXT;
